                FROM tomcat:9
                ADD addressbook.war /usr/share/tomcat/webapps
                EXPOSE 8080
                CMD ["catalina.sh", "run"]
                EOT
                sudo docker build -t myapp:v1 .
                sudo docker run -d -P myapp:v1 
                